# Generated by Django 2.2 on 2021-07-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
